[build]
   command = "echo 'No build needed for basic function'"
  functions = "netlify/functions"
  publish = "templates"

[build.environment]
  PYTHON_VERSION = "3.9"

# Add this section for function configuration
[functions]
  # Set timeout to 30 seconds for ML model operations
  "app" = { timeout = 30 }

[[redirects]]
  # Redirect API calls to the serverless function
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  # Serve static files and fallback to index.html for SPA
  from = "/*"
  to = "/templates/index.html"
  status = 200

# Function settings
[functions]
  external_node_modules = []
  node_bundler = "esbuild"