
[build]
  command = "echo 'No build needed for basic function'"
  functions = "netlify/functions"
  publish = "templates"

[build.environment]
  PYTHON_VERSION = "3.9"

# Force API redirects to go to function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true

# Everything else goes to your HTML
[[redirects]]
  from = "/*"
  to = "/templates/index.html"
  status = 200