[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "templates"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/templates/index.html"
  status = 200